### ISSUE TITLE
Tensorflow 0.11rc

### ISSUE THREAD

**Issue by avostryakov** [ritchieng/tensorflow-aws-ami#1]
Can you upgrade Tensorflow to version 0.11rc? There are so a lot of improvements in 0.10 and 0.11.

**Comment by ritchieng** [comment]
I'll look into it!

**Comment by ritchieng** [comment]
@avostryakov Currently I've updated to 0.10 for stability. I will wait until 0.11 has been tested to be stable before adding.

**Comment by avostryakov** [comment]
Thank you!
