### ISSUE TITLE
TFAMI.v4 Upcoming Release

### ISSUE THREAD

**Issue by ritchieng** [ritchieng/tensorflow-aws-ami#10]
Name Change:
- TFAMI would be changed to DLAMI (dee-luh-mi) to include PyTorch and TensorFlow (deep learning frameworks).

Essential features:
- TensorFlow r1.0 
- Latest PyTorch
- Latest Keras
- Latest TensorLayer
- CUDA 8.0
- CuDNN 5.1
- Python 2.7
- Ubuntu 16.04

Community requested changes
- Smaller EBS volume (40gb): https://github.com/ritchieng/tensorflow-aws-ami/issues/7
- Bazel build fix: https://github.com/ritchieng/tensorflow-aws-ami/issues/9

**Comment by dev-rkoshlyak** [comment]
@ritchieng can we add http://pytorch.org/
It is simple to install

**Comment by ritchieng** [comment]
@dev-rkoshlyak Yeah, I've been wanting to add that. I would probably have to change the name from `TFAMI` to `DLAMI` to include that.

You can currently just install it yourself with a simple pip command as the environment is made for it :)

**Comment by mjdietzx** [comment]
any possibility of python 3.5?

**Comment by ritchieng** [comment]
@mjdietzx I'll actually consider that. Let me think :)

**Comment by ritchieng** [comment]
Thanks for your support everyone. 

However I found out that our funding from Amazon expired and these AMIs cost us money across the regions. As such we would be discontinuing these AMIs until we've funding from Amazon. :(

**Comment by mphuget** [comment]
Ritchie, 

Maybe you can recruit other Githubers all over the Amazon regions to host your AMI. For instance, I am in EU-Ireland, so I could host it... If I remember well, the cost is just the one corresponding to storage, isn't it? 
That will be a pity for me if I no longer have access to your AMI since it saves my time not to install, I have some difficulties using TF on GPU for unknown reasons

**Comment by Innarticles** [comment]
@mphuget +1

**Comment by ritchieng** [comment]
@Innarticles @mphuget I'm discussing with my other researcher to host on in one location :) It's really a heartbreak to close this too.

In the mean time I'll be hosting it in one location.

**Comment by mphuget** [comment]
@ritchieng Do you think it is possible to reproduce the process you made to setup the AMI? I tried many, many sites proposing process to install CUDA, CuDNN, TF and for most of them, it is not working properly, especially on TF that evolves too quickly

**Comment by ritchieng** [comment]
@mphuget They're a lot of environment-specific debugging to be done that's why I can't release a standard one (tried, failed). That's the pain here. Even using a containerized installation, it's problematic. This is why I started TFAMI so everyone can just get to the deep learning part and skip the mess in installing.

**Comment by ritchieng** [comment]
@mphuget @Innarticles It's in only one region for now which has a lot of spot instances now. I sincerely apologize for the downtime for this AMI.
