### ISSUE TITLE
TFAMI are not found in ec2 ami search

### ISSUE THREAD

**Issue by amitm02** [ritchieng/tensorflow-aws-ami#11]
I've just tried to search for you AMI in the community AMIs. I get "No AMIs found matching your filter criteria"

**Comment by mphuget** [comment]
@amitm02 As mentioned by Ritchie, since he has no longer funding from Amazon to store the AMI on several regions, he was obliged to step down and to focus on the region he is

**Comment by amitm02** [comment]
@mphuget I understand. Do you know what region is still on?

**Comment by ritchieng** [comment]
@amitm02 I'm looking into hosting on just one region that is popular and has sufficient availability of GPUs if this grows (most likely in the US).

**Comment by amitm02** [comment]
@ritchieng It may sound like a silly question, but can't i just copy your AMI to my region?

**Comment by ritchieng** [comment]
@amitm02 You can! And you can post your AMI id here so I can give credit to you :)

**Comment by amitm02** [comment]
@ritchieng  for sure! send me the AMI id for me to copy and i'll do it. I'm using Ireland region.

**Comment by esolomka** [comment]
@ritchieng ready to copy for Virginia region as well :)

**Comment by esolomka** [comment]
@ritchieng any news?

**Comment by ritchieng** [comment]
@esolomka @amitm02 @mphuget  I've managed to clinch another round of funding that can maintain this project. And would be updating it in a few weeks that would last for at least 1 year. And this time I would request people to volunteer to create images in other locations in the world. Sorry for the inconvenience!  :(

**Comment by PrincipalComponent-zz** [comment]
@ritchieng Thanks for the great AMI! Would it be possible for you to share the AMI with me (privately for now)? Cheers

**Comment by sleeplessTLV** [comment]
Yes I'm interested in the AMI as well. Willing to host it on one instance on my AWS bill/account

**Comment by ritchieng** [comment]
@sleeplessTLV They would be up latest by June as my funding is almost approved to keep this up permanently.

**Comment by ritchieng** [comment]
@PrincipalComponent @esolomka @amitm02 It's in only one region for now which has a lot of spot instances now. I sincerely apologize for the downtime for this AMI. 

Oregon `ami-7e3a5b1e`
