### ISSUE TITLE
Python3.x support

### ISSUE THREAD

**Issue by ghost** [ritchieng/tensorflow-aws-ami#12]
Hi! first really thank you for your great efforts to help others use AWS more easily!

I'm a newbie in this field, and wanna know if this AMI only supports python2.7 not 3.x
so.. if this does not support python3.x, could you tell me what should I install manually or any reference site?

thanks in advance!

**Comment by ritchieng** [comment]
You've to install [TF ](https://www.tensorflow.org/install/install_linux) in python 3 using`virtualenv`. See how they use `pip3` instead of `pip`?

**Comment by ghost** [comment]
@ritchieng thanks i will try it!
