### ISSUE TITLE
AMI not showing up in search

### ISSUE THREAD

**Issue by reubenng** [ritchieng/tensorflow-aws-ami#13]
Hi, is the AMI still available? It did not show up in search for any region. I have tried all region with its corresponding AMI ID as well as 'TFAMI.v3'.

**Comment by ritchieng** [comment]
@reubenng I'll be setting it up soon as mentioned in another issue :)

**Comment by sleeplessTLV** [comment]
Any news on this? The new Book by Antonio Gulli & Sujit Pal gives your project as their sample for AWS, but it does not exist on any region...

**Comment by ankurd28** [comment]
AMI is still not showing up on search. Any updates?

**Comment by ritchieng** [comment]
@reubenng @sleeplessTLV @ankurd28 It's in only one region for now which has a lot of spot instances now. I sincerely apologize for the downtime for this AMI. 

Oregon `ami-7e3a5b1e`

**Comment by LeeKyungMoon** [comment]
@ritchieng The ami "ami-7e3a5b1e" in Oregon doesn't exist and your answer was created just two days ago. what happended?
