### ISSUE TITLE
Setup script

### ISSUE THREAD

**Issue by vgoklani** [ritchieng/tensorflow-aws-ami#2]
Could you please add the shell script that you used to build this AMI.

**Comment by ritchieng** [comment]
Due to the complexity of the installation, I most probably would not be adding the shell script any time soon. I'll release this in 1-2 month(s).

**Comment by ritchieng** [comment]
This is challenging due to the nature of how different operating systems work etc. 

Instead I'll be working on a dockerized implementation.
