### ISSUE TITLE
v1.3 Upgrades

### ISSUE THREAD

**Issue by ritchieng** [ritchieng/tensorflow-aws-ami#3]
New packages to be added for v1.3
1. TensorLayer
2. OpenCV
3. TensorFlow v0.11

Fixes
1. Compile ensuring compute capability 3.0 instead of 3.5 (p2 instances)

Pondering:
1. Dockerized implementation

**Comment by avostryakov** [comment]
I tried  TFAMI.v2 on p2. it doesn't work too. Nvidia-smi doesn't work. I started python:

ubuntu@ip-10-0-0-98:~$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
>>> sess = tf.Session()
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: ip-10-0-0-98
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: ip-10-0-0-98
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: 367.57.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:356] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.48  Sat Sep  3 18:21:08 PDT 2016
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 367.48.0
E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:296] kernel version 367.48.0 does not match DSO version 367.57.0 -- cannot find working devices in this configuration
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.

top command shows that all calculations are happening on CPU.

**Comment by avostryakov** [comment]
Sorry, after sudo reboot all works. I'll delete my comment above

**Comment by avostryakov** [comment]
I suggest updating Tensorflow to 0.11. It was released recently.

**Comment by ritchieng** [comment]
@avostryakov As stated in `FAQs`, you've to use `sudo reboot` and follow any `FAQ answers` due to the nature of TensorFlow where even a dockerized implementation has issues in being platform-neutral (frustrating I know, but imagine the whole installation, it's worst). There are a few factors but it's mainly caused by an issue with the varying drivers when you spin up an instance. 

Yes. I'll be upgrading to v0.11 after doing some tests. Thanks 👍 Do share this AMI if it works well for you!

**Comment by avostryakov** [comment]
"As stated in FAQs, you've to use sudo reboot"

Sorry again, I noticed it later.

Thank you for this AMI, it works! And what do you mean by sharing?

**Comment by ritchieng** [comment]
@avostryakov Awesome. If you know anybody who needs a simple way to use TensorFlow on AWS, do let them know :)

**Comment by ritchieng** [comment]
Upgraded with `TFAMI.v3`.

**Comment by avostryakov** [comment]
Awesome!

**Comment by ritchieng** [comment]
@avostryakov Thanks. It works on both `g2` and `p2` instances now; checked it. 

If you encounter any errors, do check FAQs. It would require just a very simple command, typically rebooting due to how Amazon AWS EC2 instances are made. :)
