### ISSUE TITLE
8G instead of 100G?

### ISSUE THREAD

**Issue by hunkim** [ritchieng/tensorflow-aws-ami#7]
I really appreciate these AMIs. Wonderful!

One issue with them is the disk space, 100G. Usually, we are using spot instances with external EBS (in order to keep our data, checkpoints, etc.), the main disk can be small. Is it possible to make small size AMIs such as 8G or 10G?

I really appreciate it.

**Comment by ritchieng** [comment]
I'll look into this :) Seems like there are some people who want it too.

**Comment by hunkim** [comment]
Sounds good. Look forward to small AMIs!

**Comment by hunkim** [comment]
I added your project to the top deep learning project list. https://github.com/hunkim/DeepLearningStars. Check it out. If you know other good deep learning projects, let me know.

**Comment by ritchieng** [comment]
@hunkim Thanks for adding! The only deep learning project I know is gaining traction is something I worked on very briefly previously that gained quite a lot of traction: https://github.com/zsdonghao/tensorlayer (1000+ stars).

It is a good alternative to Keras considering how Keras has some limitations when you want certain flexibility of TensorFlow while having an easier API. I used it for reinforcement learning in particular.

**Comment by hunkim** [comment]
I thought about this again, and it seems 8G is too small, but perhaps 20~30G (mid-size) AMIs would be appreciated.

**Comment by ritchieng** [comment]
Ok, I'll keep that in mind for the next revision.

**Comment by ritchieng** [comment]
This would be released in the upcoming TFAMI.v4: https://github.com/ritchieng/tensorflow-aws-ami/issues/10

**Comment by ghost** [comment]
@hunkim 
how nice to see you here professor Kim!!
I'm a university student in Korea and also a really big fan of yours. 
now I've been studying Deep Learning for about 2 months. 
and I could learn and understand a lot thanks to your great effort!
좋은 강의와 자료 만들어 주셔서 정말 감사드립니다! 
딥러닝을 공부하는데 정말 많은 도움이 되었습니다.
이번 가을에 홍콩에 갈 기회가 생겼는데
우연히 지나가다가 혹시 뵙게 되면 꼭 인사드리고 싶습니다!
다시 한번 감사드립니다 늦었지만 새해 복 많이 받으세요!!
